config/routes.rb
Healthyeff::Application.routes.draw do

  devise_for :users, :skip => [:registrations], :controllers => {:invitations => 'invitations'}
  as :user do
    get 'users/edit' => 'registrations#edit', :as => 'edit_user_registration'
    put 'users/edit' => 'registrations#update', :as => 'user_registration'
    match 'users/edit/update_timezone' => 'registrations#update_user_timezone', :as => :update_timezone
  end

  root to: 'days#today'

  match 'today' => 'days#today', :as => :today
  match 'past_days' => 'days#past_days', :as => :past_days
  match 'add_today' => 'days#add_today', :as => :add_today
  match 'add_days' => 'days#add_days', :as => :add_days
  match 'calendar' => 'users#calendar', :as => :calendar

  namespace :admin do
    get '' => 'list#index', :as => :list

    get 'pending' => 'pending#index', :as => :pending
    put 'update_pending' => 'pending#update', :as => :update_pending

    get 'accounting/:year/:month' => 'pdf#accounting', :as => :accounting
    get 'audit/:year/:month' => 'pdf#audit', :as => :audit
    post 'forms' => 'pdf#forms', :as => :forms
  end

  match 'admin/manage' => 'admin/manage#index', :as => :manage
  delete 'manage/:id', to: 'admin/manage#destroy', :as => :delete
  get 'manage/edit/:id', to: 'admin/manage#edit', :as => :edit
  post 'manage/edit/:id', to: 'admin/manage#update', :as => :update
  match 'manage/update_constants' => 'admin/manage#update_constants', :as => :update_constants
  post 'manage/:id', to: 'admin/manage#make_admin', :as => :make_admin

end

app/controllers/admin/list_controller.rb
class Admin::ListController < Admin::AdminController

  def index
    navigate_months()
    @date = get_date()
    @user_months = Hash.new
    User.includes(:months).all.each do |user|
      @user_months[user] = Month.get_month_model(user.id, get_month(@date), get_year(@date))
    end
    @user_months = sort(@user_months)
  end

  def navigate_months
    session[:months_ago] ||= 0
    case params[:navigate]
      when "Previous" then session[:months_ago] += 1
      when "Next" then session[:months_ago] -= 1
    end
  end

end

app/views/admin/list/index.html.haml
-#  app/views/admin/list/index.html.haml
= javascript_include_tag "admin/selectAll"

%div#top

%h1 #{link_to "<span class=\"glyphicon glyphicon-circle-arrow-left\"></span>".html_safe, admin_list_path(:navigate => "Previous"), :class => "admin_previous"} #{get_month_name(@date)} #{get_year(@date)} #{link_to "<span class=\"glyphicon glyphicon-circle-arrow-right\"></span>".html_safe, admin_list_path(:navigate => "Next"), :class => "admin_next"}

- if future_records?
  No records yet for #{get_month_name(@date)} #{get_year(@date)}.
- elsif beyond_earliest_records?
  No records from #{get_month_name(@date)} #{get_year(@date)}.
- elsif no_records?
  No records yet for this month.

- else
  %div{:style => "float: right; width: auto; display: inline-block;"}
    = button_to "Print Audit Sheet", admin_audit_path(:year => get_year(@date), :month => get_month(@date)), :method => :get, :class => "btn"

  %table#employee_list.table.table-striped
    %thead
      %tr
        %th{:style => "text-align:center; padding-left:25px; padding-right:25px"}
          %input#selectAll{:type => "checkbox", :value => "selectAll"}
        %th
          = link_to "First Name", admin_list_path(:sort => "first_name")
        %th
          = link_to "Last Name", admin_list_path(:sort => "last_name")
        %th
        %th{:style => "text-align:center"}
          = link_to "Days of Healthy Activity", admin_list_path(:sort => "days")
        %th{:style => "text-align:center"}
          Pending
        %th{:style => "text-align:center"}
          Form Received?
    %tbody
      = form_tag admin_forms_path(:year => @date.year, :month => @date.month)
      - @user_months.each do |user, month|
        %tr
          %td{:style => "text-align:center"}
            - if month.nil? or month.get_num_approved_days() == 0
            - else
              = check_box_tag "selected[" + user.last_name.to_s + "]", month.id
          %td
            = user.first_name
          %td
            = user.last_name
          %td{:style => "text-align:center"}
            = link_to "<span class =\"glyphicon glyphicon-calendar\"></span>".html_safe, calendar_path(:id => user.id)
          %td{:style => "text-align:center"}
            - if month.nil? or month.get_num_approved_days() == 0
            - else
              = month.get_num_approved_days()
          %td{:style => "text-align:center"}
            = link_to "#{month.get_num_pending_days()}", admin_pending_path unless month.nil? or month.get_num_pending_days() == 0
          %td{:style => "text-align:center"}
            - if not month.nil? and month.received_form
              ✓
    %div{:style => "float: left; width: auto; display: inline-block;"}
      = submit_tag 'Print Selected', :class => "btn"
      = submit_tag 'Mark Received', :class => "btn"