config/routes.rb
Healthyeff::Application.routes.draw do

  devise_for :users, :skip => [:registrations], :controllers => {:invitations => 'invitations'}
  as :user do
    get 'users/edit' => 'registrations#edit', :as => 'edit_user_registration'
    put 'users/edit' => 'registrations#update', :as => 'user_registration'
    match 'users/edit/update_timezone' => 'registrations#update_user_timezone', :as => :update_timezone
  end

  root to: 'days#today'

  match 'today' => 'days#today', :as => :today
  match 'past_days' => 'days#past_days', :as => :past_days
  match 'add_today' => 'days#add_today', :as => :add_today
  match 'add_days' => 'days#add_days', :as => :add_days
  match 'calendar' => 'users#calendar', :as => :calendar

  namespace :admin do
    get '' => 'list#index', :as => :list

    get 'pending' => 'pending#index', :as => :pending
    put 'update_pending' => 'pending#update', :as => :update_pending

    get 'accounting/:year/:month' => 'pdf#accounting', :as => :accounting
    get 'audit/:year/:month' => 'pdf#audit', :as => :audit
    post 'forms' => 'pdf#forms', :as => :forms
  end

  match 'admin/manage' => 'admin/manage#index', :as => :manage
  delete 'manage/:id', to: 'admin/manage#destroy', :as => :delete
  get 'manage/edit/:id', to: 'admin/manage#edit', :as => :edit
  post 'manage/edit/:id', to: 'admin/manage#update', :as => :update
  match 'manage/update_constants' => 'admin/manage#update_constants', :as => :update_constants
  post 'manage/:id', to: 'admin/manage#make_admin', :as => :make_admin

end

app/views/admin/manage.html.haml
%h1 Manage
%div.manage_content.settings
  %h2 Settings
  = form_for(@constant, url: update_constants_path, :html => {class: "form-inline"}) do |f|
    %p
      = f.label :curr_rate, 'Reimbursement Rate: ', :class => 'rate_label'
      = f.number_field :curr_rate, :value => @constant.curr_rate, :class => "rate_input", :id => 'rate_input'
      dollars per day
    = f.submit 'Update', :confirm => "Are you sure you want to update the reimbursement rate?", :class => "btn"
%br
%div.manage_content.employees
  %h2 Employees
  = link_to "<span class=\"glyphicon glyphicon-plus-sign\"></span> New employee".html_safe, new_user_invitation_path, :class => "add_new_employee"
  
  %table#movies.table.table-striped
    %thead
      %tr
        %th Last Name
        %th First Name
        %th Email
        %th Change?
        %th Remove?
    %tbody
      - @users.each do |user|
        %tr
          %td= user.last_name
          %td= user.first_name
          %td= user.email
          %td= link_to "<span class =\"glyphicon glyphicon-pencil\"></span> Edit".html_safe, edit_path(user), :class => 'edit_user'
          %td= link_to "<span class =\"glyphicon glyphicon-trash\"></span> Delete".html_safe, delete_path(user),   :method => :delete, :confirm => "Are you sure you want to delete employee #{user.first_name} #{user.last_name}?"

app/views/admin/pending.html.haml
-#  app/views/admin/pending.html.haml
%h1 Activities Pending Approval

= form_tag admin_update_pending_path, :method => :put
%table#pending.table.table-striped
  %thead
    %tr
      %th{:style => "text-align:center"} Select
      %th First Name
      %th Last Name
      %th Date
      %th Reason
  %tbody
    - @days.each do |day|
      %tr
        %td{:style => "text-align:center"}= check_box_tag "selected[]", day.id
        %td= day.user.first_name
        %td= day.user.last_name
        %td= day.date.strftime("%m/%d/%Y")
        %td= day.reason

%p
= submit_tag 'Approve', :class => "btn btn-success"
= submit_tag 'Deny', :class => "btn btn-danger"

app/views/admin/tally.html.haml
-#  app/views/admin/tally.html.haml
%h1 EFF's Healthy Lifestyles Program
%h2 Monthly Accounting: #{@date.strftime("%B")} #{@date.strftime("%Y")}

%p Employee Name: #{@first_name} #{@last_name}

%table#monthly_acct
  %tbody
    - for i in 1..@num_days / 2
      %tr
        %td= i.to_s
        %td _______
        %td= (i + (@num_days/2)).to_s
        %td _______
        - if i == @num_days / 2 and (@num_days % 2) == 1
          %td= @num_days.to_s
          %td _______

%p Total number of days: #{@user_days}
%p Reimbursable amount (days x $10): $#{@user_days * 10}

%p I certify that I spent at least one hour engaged in reimbursable personal health-focused behavior on each of the above dates.
%br
%p Signature: _______________________ &nbsp;&nbsp;&nbsp;&nbsp; Date: ________