config/routes.rb
Healthyeff::Application.routes.draw do

  devise_for :users, :skip => [:registrations], :controllers => {:invitations => 'invitations'}
  as :user do
    get 'users/edit' => 'registrations#edit', :as => 'edit_user_registration'
    put 'users/edit' => 'registrations#update', :as => 'user_registration'
    match 'users/edit/update_timezone' => 'registrations#update_user_timezone', :as => :update_timezone
  end

  root to: 'days#today'

  match 'today' => 'days#today', :as => :today
  match 'past_days' => 'days#past_days', :as => :past_days
  match 'add_today' => 'days#add_today', :as => :add_today
  match 'add_days' => 'days#add_days', :as => :add_days
  match 'calendar' => 'users#calendar', :as => :calendar

  namespace :admin do
    get '' => 'list#index', :as => :list

    get 'pending' => 'pending#index', :as => :pending
    put 'update_pending' => 'pending#update', :as => :update_pending

    get 'accounting/:year/:month' => 'pdf#accounting', :as => :accounting
    get 'audit/:year/:month' => 'pdf#audit', :as => :audit
    post 'forms' => 'pdf#forms', :as => :forms
  end

  match 'admin/manage' => 'admin/manage#index', :as => :manage
  delete 'manage/:id', to: 'admin/manage#destroy', :as => :delete
  get 'manage/edit/:id', to: 'admin/manage#edit', :as => :edit
  post 'manage/edit/:id', to: 'admin/manage#update', :as => :update
  match 'manage/update_constants' => 'admin/manage#update_constants', :as => :update_constants
  post 'manage/:id', to: 'admin/manage#make_admin', :as => :make_admin

end

app/models/day.rb
class Day < ActiveRecord::Base
  include ErrorMessages, DateFormat

  attr_accessible :date, :total_time, :reason, :approved, :month_id, :denied, :timezone
  validates :date, :reason, presence: true
  validate :valid_total, :valid_date
  belongs_to :month
  has_many :activities, :dependent => :destroy
  accepts_nested_attributes_for :activities, :allow_destroy => true

  # Returns the total number of activity-days pending approval
  def self.num_pending
    Day.count(:conditions => {:approved => false, :denied => false})
  end

  def self.create_day(date, approved, reason, timezone="Pacific Time (US & Canada)")
    return Day.new({:date => date,
                    :approved => approved,
                    :denied => false,
                    :total_time => 0,
                    :reason => reason,
                    :timezone => timezone})
  end

  def user ; self.month.user ; end

  def save_with_activities(activities)
    notice = ""
    self.save!
    activities.each do |activity|
      activity.day_id = self.id
      activity.save!
      notice += activity_recorded(activity.name, activity.duration, format_date(date))
    end
    return notice
  end

  def valid_total
    if total_time < 60
      errors.add(:total, NOT_ENOUGH)
    elsif total_time > 1440
      errors.add(:total, NOT_TOO_HIGH)
    end
  end

  def valid_date
    unless approved
      today = get_today(self.timezone)
      start_date = today.beginning_of_month
      start_date =  today.ago(1.month).beginning_of_month if get_day(today) < 6
      end_date = today.prev_day
      check_date_in_range(start_date, end_date)
    end
  end

  def check_date_in_range(start_date, end_date)
    unless ((start_date.to_date)..(end_date.to_date)) === (date.to_date)
      errors.add(:date, date_out_of_range(format_date(date)))
    end
  end

  def approve_day
    self.approved = true
    self.save!
    month = self.month
    month.num_of_days += 1
    month.save!
  end

end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  include DateFormat

  before_filter :check_logged_in, :force_password_change

  def today
    restful_redirect
    @date = get_today(current_user.current_timezone)
    @day = Day.create_day(@date, true, "", current_user.current_timezone)
    @day.activities.append(Activity.new())
    month = Month.get_month_model(current_user.id, get_month(@date), get_year(@date))
    flash[:alert] = repeat_date(format_date(@date)) if month != nil && month.contains_date?(@date)
  end

  def past_days
    @month = Month.new()
    day = Day.new()
    @month.days.append(day)
    day.activities.append(Activity.new())
    today = get_today(current_user.current_timezone)
    @end_date = today.prev_day
    @start_date = get_day(today) < 6 ? today.ago(1.month).beginning_of_month : today.beginning_of_month
    @previously_inputted = Month.get_inputted_dates(current_user.id, @start_date, @end_date)
  end

  def restful_redirect
    if request.fullpath != '/today'
      flash.keep
      redirect_to today_path
    end
  end

  def check_simple_captcha
    if Rails.env.production?
      return simple_captcha_valid?
    else
      return true
    end
  end

  def error_recovery(error)
    flash[:notice] = nil
    flash[:alert] = error.message if flash[:alert] == nil
  end

  def bad_captcha
    flash[:alert] = BAD_CAPTCHA
    raise Exception
  end

  def empty_fields_notice
    flash[:alert] = EMPTY_FIELDS
    raise Exception
  end

  def add_today
    begin
      add(false, :day, :activities_attributes)
    rescue Exception => e
      error_recovery(e)
      redirect_to today_path
    end
  end

  def add_days
    begin
      add(true, :month, :days_attributes)
    rescue Exception => e
      error_recovery(e)
      redirect_to past_days_path
    end
  end

  def add(has_past_days, outer_sym, inner_sym)
    bad_captcha unless check_simple_captcha
    empty_fields_notice() if params[outer_sym] == nil || params[outer_sym][inner_sym] == nil
    if has_past_days then create_past_days() else create_single_day(params[outer_sym], true) end
    redirect_to calendar_path #success
  end

  def create_single_day(day, approved)
    date = day[:date]
    date = get_date(date) unless approved
    @day = Day.create_day(date, approved, params[:days][:reason], current_user.current_timezone)
    flash[:notice] = "" if flash[:notice] == nil
    flash[:notice] += @day.save_with_activities(validate_single_day(day[:activities_attributes], @day))
    Month.update_month(current_user.id, @day)
  end

  def create_past_days
    params[:month][:days_attributes].each do |id, day|
      empty_fields_notice() if day[:activities_attributes] == nil
      check_day(day)
    end
    save_past_days()
  end

  def check_day(day)
    begin
      date = get_date(day[:date])
      @day = Day.create_day(date, false, params[:days][:reason], current_user.current_timezone)
      validate_single_day(day[:activities_attributes], @day)
    rescue ArgumentError
      #case where Date.parse throws an ArgumentError for having invalid date field
      flash[:alert] = INVALID_DATE
      raise Exception
    end
  end

  def validate_single_day(activity_list, day)
    activities = validate_single_day_activities(activity_list, day)
    validate_model(day)
    check_date_already_input(day.date)
    return activities
  end

  def validate_single_day_activities(activity_list, day)
    activities = []
    activity_list.each do |id, activity|
      new_activity = Activity.create_activity(activity, day)
      validate_model(new_activity)
      activities += [new_activity]
    end
    return activities
  end

  def save_past_days
    params[:month][:days_attributes].each do |id, day|
      create_single_day(day, false)
    end
  end

  def validate_model(model)
    unless model.valid?
      flash[:alert] = model.errors.full_messages[0]
      raise Exception
    end
  end

  def check_date_already_input(date)
    month = Month.get_month_model(current_user.id, get_month(date), get_year(date))
    return unless month != nil && month.contains_date?(date)
    flash[:alert] = repeat_date format_date(date)
    raise Exception
  end

end

app/views/days/_activity_fields.html.haml
%div.activity_container
  %p.activity.field
    = f.label :name, 'Activity: ', :class => 'activity_label'
    = f.text_field :name, :placeholder  => '(optional) ex. Running', :value => (session[:name] != nil ? session[:name] : "")
    = f.label :duration, 'Duration (minutes): ', :class => 'activity_label'
    = f.number_field :duration, :value => "60", :placeholder => '(in minutes) ex. 30', :required => "required"
    = link_to_function "<span class=\"glyphicon glyphicon-minus-sign\"></span>".html_safe, "remove_fields(this)", :class => "remove_activity"

app/views/days/_day_fields.html.haml
%div.day.field
  = f.label :date, 'On '
  = f.text_field :date, :placeholder => 'mm/dd/yyyy', 'data-provide' => "datepicker", 'data-date-format' => "mm/dd/yyyy", 'data-date-start-date' => "#{@start_date.strftime("%m/%d/%Y")}", 'data-date-end-date' => "#{@end_date.strftime("%m/%d/%Y")}", 'data-date-dates-disabled' => @previously_inputted, :class => 'datepicker', autocomplete: "off", :required => "required"
  = link_to_function "<span class=\"glyphicon glyphicon-minus-sign\"></span>".html_safe, "remove_fields(this)", :class => "remove_day"
  %br
  %br
  = f.fields_for :activities do |builder|
    = render "activity_fields", :f => builder
  %p
    = link_to_add_fields "<span class=\"glyphicon glyphicon-plus-sign\"></span> Add Activity".html_safe, f, :activities

app/views/days/multiple_days.html.haml
= form_for @user, url: add_days_path()  do |f|
  %p
    Healthy Activity Form
  = f.fields_for :days do |builder|
    = render "day_fields", :f => builder
  %p
    = link_to_add_fields "Add Day", f, :days
  = label :days, :reason, 'Reason for inputting multiple days'
  = text_field :days, :reason
  %br
  (Note: activity for all days besides the current day will be sent to admin for approval)
  %p 
    = show_simple_captcha(:label => "Enter before submitting", :placeholder => "", :refresh_button_text => "Refresh text")
    = f.submit 'Submit'

app/views/days/past_days.html.haml
%p.notice 
  %span.glyphicon.glyphicon-info-sign
  Your Current Timezone is set to #{current_user.current_timezone}. 
  = link_to "Update Timezone", edit_user_registration_path
= form_for(@month, url: add_days_path(), :html => {class: "form-inline"})  do |f|
  %p.form
  = f.fields_for :days do |builder|
    = render "day_fields", :f => builder
  %p
    = link_to_add_fields "<span class=\"glyphicon glyphicon-plus-sign\"></span> Add Day".html_safe, f, :days
  = label :days, :reason, 'Reason for inputting past days:'
  = text_field :days, :reason, :required => "required"
  %p.notice 
    %span.glyphicon.glyphicon-info-sign
    Activities for all past days will be sent to admin for approval.
  
  %p 
    = show_simple_captcha(:label => "Enter before submitting", :placeholder => "", :refresh_button_text => "Refresh text")

    = f.submit 'Submit', :class => 'submit btn'

app/views/days/today.html.haml
= form_for(@day, url: add_today_path(), :html => {class: "form-inline"}) do |f|
  %p.form
  %div.today.field
    %span.glyphicon.glyphicon-calendar.title_today
    %span
      = f.label :date, "Today #{@date.strftime("%m/%d/%Y")}", :class => "title_today"
      = link_to "#{current_user.current_timezone}", edit_user_registration_path, :class => "title_today"
    = f.hidden_field :date, value: @date
    = f.fields_for :activities do |builder|
      = render "activity_fields", :f => builder
      = link_to_add_fields "<span class=\"glyphicon glyphicon-plus-sign\"></span> Add Activity".html_safe, f, :activities
 
  %p 
    = show_simple_captcha(:label => "Enter before submitting", :placeholder => "", :refresh_button_text => "Refresh text")
    = hidden_field :days, :reason, value: "none"

    = f.submit 'Submit', :class => "btn"
= link_to "Input Past Days", past_days_path