config/routes.rb
Healthyeff::Application.routes.draw do

  devise_for :users, :skip => [:registrations], :controllers => {:invitations => 'invitations'}
  as :user do
    get 'users/edit' => 'registrations#edit', :as => 'edit_user_registration'
    put 'users/edit' => 'registrations#update', :as => 'user_registration'
    match 'users/edit/update_timezone' => 'registrations#update_user_timezone', :as => :update_timezone
  end

  root to: 'days#today'

  match 'today' => 'days#today', :as => :today
  match 'past_days' => 'days#past_days', :as => :past_days
  match 'add_today' => 'days#add_today', :as => :add_today
  match 'add_days' => 'days#add_days', :as => :add_days
  match 'calendar' => 'users#calendar', :as => :calendar

  namespace :admin do
    get '' => 'list#index', :as => :list

    get 'pending' => 'pending#index', :as => :pending
    put 'update_pending' => 'pending#update', :as => :update_pending

    get 'accounting/:year/:month' => 'pdf#accounting', :as => :accounting
    get 'audit/:year/:month' => 'pdf#audit', :as => :audit
    post 'forms' => 'pdf#forms', :as => :forms
  end

  match 'admin/manage' => 'admin/manage#index', :as => :manage
  delete 'manage/:id', to: 'admin/manage#destroy', :as => :delete
  get 'manage/edit/:id', to: 'admin/manage#edit', :as => :edit
  post 'manage/edit/:id', to: 'admin/manage#update', :as => :update
  match 'manage/update_constants' => 'admin/manage#update_constants', :as => :update_constants
  post 'manage/:id', to: 'admin/manage#make_admin', :as => :make_admin

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
    %title Healthy EFF
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tags
    = nav_bar fixed: :left, brand: "<img class=\"logo\" src=\"#{image_path('eff.png')}\">".html_safe, responsive: true do
      - if user_signed_in?
        = menu_group do
          = menu_divider
          - if current_user.admin
            = menu_item "<span class=\"glyphicon glyphicon-user\"></span> Admin".html_safe, admin_list_path
            = menu_divider
            = menu_item "<span class=\"glyphicon glyphicon-paperclip\"></span> Manage".html_safe, manage_path
            = menu_divider
            - if Day.num_pending > 0
              = menu_item "<span class=\"glyphicon glyphicon-envelope\"></span><span class=\"badge\">#{Day.num_pending}</span> Pending".html_safe, admin_pending_path, :class => "pending_link"
              = menu_divider
          = menu_item "<span class=\"glyphicon glyphicon-calendar\"></span> Calendar".html_safe, calendar_path, :class => "calendar_link"
          = menu_divider
        = menu_group pull: :right do
          = menu_divider
          = menu_item "<span class=\"glyphicon glyphicon-cog\"></span> Settings".html_safe, edit_user_registration_path, :class => "settings_link"
          = menu_divider
          = menu_item "Sign Out", destroy_user_session_path, :method => :delete
  %body
    %div.content
      -if notice
        %p.notice
          %span.glyphicon.glyphicon-info-sign
          = notice
      -if alert
        %p.alert
          %span.glyphicon.glyphicon-exclamation-sign
          = alert
      = yield